title: Leran Zhao
description: "Berkeley → Hong Kong. Recruiting, writing, building."
url: "https://leranzhao.github.io"
baseurl: ""
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
